//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSoft.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminTable
    {
        public string id_admin { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id_sex { get; set; }
    
        public virtual sexTable sexTable { get; set; }
    }
}
