//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProSoft.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProSoftEntities : DbContext
    {
        public ProSoftEntities()
            : base("name=ProSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminTable> adminTable { get; set; }
        public virtual DbSet<orderTable> orderTable { get; set; }
        public virtual DbSet<partnerTable> partnerTable { get; set; }
        public virtual DbSet<productTable> productTable { get; set; }
        public virtual DbSet<sexTable> sexTable { get; set; }
        public virtual DbSet<statusTable> statusTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<userTable> userTable { get; set; }
    }
}
